export default icons = {
    close: require('../assets/icons/close.png'),
    add_persion: require('../assets/icons/add_persion.png'),
    favourite: require('../assets/icons/favourite.png'),
    help_center: require('../assets/icons/help_center.png'),
    location: require('../assets/icons/location.png'),
    logout: require('../assets/icons/logout.png'),
    wallet: require('../assets/icons/wallet.png'),
    home: require('../assets/icons/home.png'),
    notification: require('../assets/icons/notification.png'),
    setting: require('../assets/icons/setting.png'),
    menu: require('../assets/icons/menu.png'),
    search: require('../assets/icons/search.png'),
    filter: require('../assets/icons/filter.png'),
    down_arrow: require('../assets/icons/expand.png'),
    cart: require('../assets/icons/cart.png'),
    calories: require('../assets/icons/calories.png'),
    favouriteFilled: require('../assets/icons/favourite-filled.png'),
}
